name: Publish .NET package to NuGet

on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Set your desired .NET version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      # Run tests (optional, remove if not needed)
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # Pack the project
      - name: Pack the project
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      # Publish the package to NuGet
      - name: Publish package to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_GALLERY_API }} --source https://api.nuget.org/v3/index.json
